### ISSUE TITLE
Soap Error

### ISSUE THREAD

**Issue by byyasinc** [ismail0234/aras-kargo-php-api#3]
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://customerservices.araskargo.com.tr/ArasCargoCustomerIntegrationService/ArasCargoIntegrationService.svc?wsdl' : Premature end of data in tag html line 1

Hatası alıyorum bağlantıda, çözüm bulamadım nedendir?

**Comment by ismail0234** [comment]
Merhaba, sorunu çözebildiniz mi?

**Comment by byyasinc** [comment]
Merhaba,

Evet sorun benim bağlantımdan kaynaklıymış :) Bu arada metodlar içerisine
30 nolu gelen kargo metodunu ekleme şansınız olur mu? Veya bana commit izni
verirseniz ben güncelleme atabilirim.

2 Ağu 2021 Pzt, saat 14:53 tarihinde İsmail ***@***.***> şunu
yazdı:

**Comment by ismail0234** [comment]
Merhaba,

Repoyu forklayarak gerekli düzenlemeleri yaptıktan sonra bir çekme isteği gönderebilirsiniz. Gerekli kontrolleri sağladıktan sonra repo ile birleştirebilirim.
