### ISSUE TITLE
Aras kargo servis bilgileri alma

### ISSUE THREAD

**Issue by ahmetbasdan** [ismail0234/aras-kargo-php-api#4]
Merhaba İsmail Bey,
Aras kargo apisi için servis bilgileri almaya çalışıyorum. Fakat aradığım numaralarda destek personelleri konuya biraz uzaklar. Aras kargo servis kullanıcı adı ve şifre mi alabilmek için nasıl bir yol izlemeliyim?

**Comment by ismail0234** [comment]
Merhaba,

Aras kargo servis bilgilerini alalı aradan uzun zaman geçti. En son hatırladığım kadarı ile aras kargo kurumsal sayfasından (https://esasweb.araskargo.com.tr/) giriş yaptıktan sonra sol menüde bir bölümün içerisinde yer alıyordu.
